function skillsMember() {
    return [
        'JavaScript',
        'React',
        'NodeJS',
        'TypeScript',
        'GraphQL',
        'MongoDB',
        'PostgreSQL',
        'Docker',
        'Kubernetes',
        'AWS',
        'GCP',
        'Azure',
        'Heroku',
        'Netlify',
        'Vercel',
        'Jest',
        'Cypress',
        'Puppeteer',
        'React Testing Library',
        'Git',
        'GitHub',
        'GitLab',
        'Bitbucket',
        'Travis CI',
        'CircleCI',
        'Jenkins',
        'GitLab CI',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Jira',
        'Trello',
        'Asana',
        'Monday',
        'Notion',
    ]
}